version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - mcclowes
  assignees:
  - mcclowes
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
    - 5.1.1
    - 5.1.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.8
  - dependency-name: marked
    versions:
    - 1.2.7
    - 1.2.8
    - 2.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
